[package]
name = "dagger-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
dagger-sdk = "0.19"
eyre = "0.6"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
