name: Container Scanner

on:
  workflow_dispatch: # Triggers the workflow manually
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt:latest
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt-envoy:latest
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt-k8s-operator:latest
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:latest
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt-rag-engine:latest
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/bionic-gpt/bionicgpt-airbyte-connector:latest